import 'package:blog_app_clean_architecture/core/common/cubit/app_user/app_user_cubit.dart';
import 'package:blog_app_clean_architecture/core/network/connection_checker.dart';
import 'package:blog_app_clean_architecture/core/secrets/app_secrets.dart';
import 'package:blog_app_clean_architecture/feature/auth/data/datasources/auth_remote_data_source.dart';
import 'package:blog_app_clean_architecture/feature/auth/data/repositories/auth_repositories_impl.dart';
import 'package:blog_app_clean_architecture/feature/auth/domain/repository/auth_repository.dart';
import 'package:blog_app_clean_architecture/feature/auth/domain/usecases/current_user.dart';
import 'package:blog_app_clean_architecture/feature/auth/domain/usecases/user_login.dart';
import 'package:blog_app_clean_architecture/feature/auth/domain/usecases/user_sign_up.dart';
import 'package:blog_app_clean_architecture/feature/auth/presentation/bloc/auth_bloc.dart';
import 'package:blog_app_clean_architecture/feature/blog/data/datasources/blog_local_data_source.dart';
import 'package:blog_app_clean_architecture/feature/blog/data/datasources/blog_remote_data_source.dart';
import 'package:blog_app_clean_architecture/feature/blog/data/repositories/blog_repository_impl.dart';
import 'package:blog_app_clean_architecture/feature/blog/domain/repositories/blog_repository.dart';
import 'package:blog_app_clean_architecture/feature/blog/domain/usecase/get_all_blogs.dart';
import 'package:blog_app_clean_architecture/feature/blog/domain/usecase/upload_blog.dart';
import 'package:blog_app_clean_architecture/feature/blog/presentation/bloc/blog_bloc.dart';
import 'package:get_it/get_it.dart';
// import 'package:hive/hive.dart';
import 'package:internet_connection_checker/internet_connection_checker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

part 'init_dependencies.main.dart';
